//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Icm.ContextConsole.My_Project.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contexts list.
        /// </summary>
        internal static string contexts_listtitle {
            get {
                return ResourceManager.GetString("contexts_listtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find action {0} inside context {1}.
        /// </summary>
        internal static string executecommand_actionnotfound_2 {
            get {
                return ResourceManager.GetString("executecommand_actionnotfound_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find context {0}.
        /// </summary>
        internal static string executecommand_contextnotfound_1 {
            get {
                return ResourceManager.GetString("executecommand_contextnotfound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error at character {0} (unclosed quotes or backslash at end, problem started at {1}).
        /// </summary>
        internal static string executecommand_parseerror_2 {
            get {
                return ResourceManager.GetString("executecommand_parseerror_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT.
        /// </summary>
        internal static string help_current {
            get {
                return ResourceManager.GetString("help_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions of {0}.
        /// </summary>
        internal static string help_title_1 {
            get {
                return ResourceManager.GetString("help_title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions of {0} ({1}).
        /// </summary>
        internal static string help_title_2 {
            get {
                return ResourceManager.GetString("help_title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bye!.
        /// </summary>
        internal static string quit_bye {
            get {
                return ResourceManager.GetString("quit_bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows subcontexts of root.
        /// </summary>
        internal static string root_contexts {
            get {
                return ResourceManager.GetString("root_contexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows help.
        /// </summary>
        internal static string root_help {
            get {
                return ResourceManager.GetString("root_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quits the application.
        /// </summary>
        internal static string root_quit {
            get {
                return ResourceManager.GetString("root_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: change to {0} subcontext.
        /// </summary>
        internal static string root_use {
            get {
                return ResourceManager.GetString("root_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using context {0}.
        /// </summary>
        internal static string use_message_1 {
            get {
                return ResourceManager.GetString("use_message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context (leave blank for Main).
        /// </summary>
        internal static string use_prompt {
            get {
                return ResourceManager.GetString("use_prompt", resourceCulture);
            }
        }
    }
}
