'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Icm.ContextConsole.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contexts list.
        '''</summary>
        Friend ReadOnly Property contexts_listtitle() As String
            Get
                Return ResourceManager.GetString("contexts_listtitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Could not find action {0} inside context {1}.
        '''</summary>
        Friend ReadOnly Property executecommand_actionnotfound_2() As String
            Get
                Return ResourceManager.GetString("executecommand_actionnotfound_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Could not find context {0}.
        '''</summary>
        Friend ReadOnly Property executecommand_contextnotfound_1() As String
            Get
                Return ResourceManager.GetString("executecommand_contextnotfound_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Parse error at character {0} (unclosed quotes or backslash at end, problem started at {1}).
        '''</summary>
        Friend ReadOnly Property executecommand_parseerror_2() As String
            Get
                Return ResourceManager.GetString("executecommand_parseerror_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CURRENT.
        '''</summary>
        Friend ReadOnly Property help_current() As String
            Get
                Return ResourceManager.GetString("help_current", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Actions of {0}.
        '''</summary>
        Friend ReadOnly Property help_title_1() As String
            Get
                Return ResourceManager.GetString("help_title_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Actions of {0} ({1}).
        '''</summary>
        Friend ReadOnly Property help_title_2() As String
            Get
                Return ResourceManager.GetString("help_title_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bye!.
        '''</summary>
        Friend ReadOnly Property quit_bye() As String
            Get
                Return ResourceManager.GetString("quit_bye", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Shows help.
        '''</summary>
        Friend ReadOnly Property root_help() As String
            Get
                Return ResourceManager.GetString("root_help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Quits the application.
        '''</summary>
        Friend ReadOnly Property root_quit() As String
            Get
                Return ResourceManager.GetString("root_quit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Using context {0}.
        '''</summary>
        Friend ReadOnly Property use_message_1() As String
            Get
                Return ResourceManager.GetString("use_message_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Context (leave blank for Main).
        '''</summary>
        Friend ReadOnly Property use_prompt() As String
            Get
                Return ResourceManager.GetString("use_prompt", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
